name: primeira pipeline

on:
  push:
    branches: [main]

jobs:

  linter:
    name: Análise de Código (Linter)
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar linter
        run: pip install flake8
      - name: Executar Linter
        run: flake8 calculadora.py test_calculadora.py --count --show-source --statistics

  teste_soma:
    name: Teste de Soma
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de soma
        run: pytest test_calculadora.py::test_soma

  teste_subtracao:
    name: Teste de subtracao
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de subtracao
        run: pytest test_calculadora.py::test_subtracao

  teste_multiplicacao:
    name: Teste de multiplicacao
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de multiplicacao
        run: pytest test_calculadora.py::test_multiplicacao

  teste_divisao:
    name: Teste de divisao
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de divisao
        run: pytest test_calculadora.py::test_divisao

  deploy:
    name: Simular Deploy
    needs: [teste_soma, teste_subtracao, teste_multiplicacao, teste_divisao] 
    runs-on: ubuntu-latest
    steps:
      - name: Confirmar Deploy
        run: echo "Todos os testes individuais passaram! Deploy realizado com sucesso."